complete homework
FeralBerry/hw3-1 pull request #1
Opened 2024-02-09 06:35 UTC by FeralBerry

2024-02-14 14:20 UTC, OlgaLugacheva requested changes

2024-02-14 14:20 UTC, OlgaLugacheva commented on src/main/java/ru/hogwarts/school/controllers/FacultyController.java
> +    @GetMapping("/read")
/read не нужен , по Get и так понятно, что это чтение

2024-02-14 14:20 UTC, OlgaLugacheva commented on src/main/java/ru/hogwarts/school/controllers/FacultyController.java
> +    @PutMapping("/put")
аналогично /put лишнее

2024-02-14 14:20 UTC, OlgaLugacheva commented on src/main/java/ru/hogwarts/school/controllers/FacultyController.java
> +    @DeleteMapping("/delete/{id}")
/delete убрать

2024-02-14 14:20 UTC, OlgaLugacheva commented on src/main/java/ru/hogwarts/school/controllers/FacultyController.java
> +    @GetMapping("/sort_by_color")
в мапппинге лучше использовать тире

2024-02-14 14:20 UTC, OlgaLugacheva commented on src/main/java/ru/hogwarts/school/controllers/StudentController.java
>      @GetMapping("/read")
здесь те же комментарии что и в другом контроллере

2024-02-16 17:04 UTC, OlgaLugacheva requested changes

2024-02-16 17:04 UTC, OlgaLugacheva commented on src/main/java/ru/hogwarts/school/models/Student.java
> +    private int faculty_id;
это лишнее поле - уже ведь есть связка ниже

2024-02-16 17:04 UTC, OlgaLugacheva commented on src/main/java/ru/hogwarts/school/models/Student.java
> +    }
лишнее, но нужен геттер для faculty и его потом использовать

2024-02-16 17:04 UTC, OlgaLugacheva commented on src/main/java/ru/hogwarts/school/models/Faculty.java
> +    private Collection<Student> students;
нужен геттер для этого поля

2024-02-16 17:04 UTC, OlgaLugacheva commented on src/main/java/ru/hogwarts/school/controllers/FacultyController.java
> +        return facultyService.findById(id);
в этом эндпоинте нужно найти всех студентов факультета, а сейчас тут находится факультет по id 
в помощь - геттер для коллекции студентов

2024-02-16 17:04 UTC, OlgaLugacheva commented on src/main/java/ru/hogwarts/school/controllers/StudentController.java
> +    public List<Student> findAllByFaculty_id(@RequestBody long id){
тут же нужно найти факультет, к кторому студент относится, также подойдет геттер для факультета 
ненужные неиспользуемые методы в репозиториях  тогда можно будет удалить

2024-02-28 08:17 UTC, dmitry-bizin commented on src/test/java/ru/hogwarts/school/services/FacultyServiceTest.java
> +    }
это не нужно, надо просто над классом повесить `@AutoConfigureMockMvc`

2024-02-28 08:17 UTC, dmitry-bizin commented on src/test/java/ru/hogwarts/school/services/FacultyServiceTest.java
> +@ExtendWith(MockitoExtension.class)
это не нужно

2024-02-28 08:17 UTC, dmitry-bizin commented on src/test/java/ru/hogwarts/school/services/FacultyServiceTest.java
> +@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
зачем порт рандомный? ты не используешь testresttemplate

2024-02-28 08:17 UTC, dmitry-bizin commented on src/test/java/ru/hogwarts/school/services/FacultyServiceTest.java
> +    private WebApplicationContext webApplicationContext;
не нужно

2024-02-28 08:18 UTC, dmitry-bizin commented on src/test/java/ru/hogwarts/school/services/FacultyServiceTest.java
> +                .andExpect(jsonPath("$.*").isNotEmpty());
проверка слабая, что толку, что не пустой объект вернулся? надо проверить, какой именно

2024-02-28 08:19 UTC, dmitry-bizin commented on src/test/java/ru/hogwarts/school/services/FacultyServiceTest.java
> +        Assertions.assertEquals("",mockMvc.perform(MockMvcRequestBuilders
ой, а почему так? почему бы не через assertJ проверить?

2024-02-28 08:19 UTC, dmitry-bizin commented on src/test/java/ru/hogwarts/school/services/FacultyServiceTest.java
> +                .getContentAsString().contains(color));
проверка слабая, что толку, хорошо бы проверить все поля объекта

2024-02-28 08:25 UTC, dmitry-bizin commented on src/test/java/ru/hogwarts/school/services/FacultyServiceTest.java
> +                .andExpect(jsonPath("$[*].id").value(id)); //выдает ошибку при сравнении 1 и 1
потому что ты пытаешься взять id у всех элементов массива сразу, надо взять у какого-то одного, например, первого
```suggestion
                .andExpect(jsonPath("$[0].id").value(id)); //выдает ошибку при сравнении 1 и 1
```
а до этого лучше добавить проверку
`.andExpect(jsonPath("$.length()").value(1))`

2024-02-28 08:26 UTC, dmitry-bizin commented on src/test/java/ru/hogwarts/school/services/StudentServiceTest.java
> +@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
зачем порт рандомный? ты не используешь testresttemplate

2024-02-28 08:26 UTC, dmitry-bizin commented on src/test/java/ru/hogwarts/school/services/StudentServiceTest.java
> +@ExtendWith(MockitoExtension.class)
это не нужно

2024-02-28 08:26 UTC, dmitry-bizin commented on src/test/java/ru/hogwarts/school/services/StudentServiceTest.java
> +    private WebApplicationContext webApplicationContext;
не нужно

2024-02-28 08:27 UTC, dmitry-bizin commented on src/test/java/ru/hogwarts/school/services/StudentServiceTest.java
> +    }
это не нужно, надо просто над классом повесить `@AutoConfigureMockMvc`

2024-02-28 08:27 UTC, dmitry-bizin commented on src/test/java/ru/hogwarts/school/services/StudentServiceTest.java
> +                .andExpect(jsonPath("$.*").isNotEmpty());
слабая проверка

2024-02-28 08:27 UTC, dmitry-bizin commented on src/test/java/ru/hogwarts/school/services/StudentServiceTest.java
> +        Assertions.assertEquals("",mockMvc.perform(MockMvcRequestBuilders
лучше через assertJ

2024-02-28 08:28 UTC, dmitry-bizin commented on src/test/java/ru/hogwarts/school/services/StudentServiceTest.java
> +        studentService.findAllByAge(age).forEach(s->Assertions.assertEquals(age,s.getAge()));
мм, в чём смысл? где запрос к эндпоинту?

2024-02-28 08:28 UTC, dmitry-bizin commented on src/test/java/ru/hogwarts/school/services/StudentServiceTest.java
> +        );
мм, в чём смысл? где запрос к эндпоинту?

2024-02-28 08:28 UTC, dmitry-bizin commented on src/test/java/ru/hogwarts/school/services/StudentServiceTest.java
> +        Assertions.assertEquals(faculty,studentService.findFaculty(1L));
мм, в чём смысл? где запрос к эндпоинту?

2024-02-29 08:25 UTC, dmitry-bizin commented on src/test/java/ru/hogwarts/school/Hw31ApplicationTest.java
>  @ExtendWith(MockitoExtension.class)
не нужна аннотация

2024-02-29 08:26 UTC, dmitry-bizin commented on src/test/java/ru/hogwarts/school/Hw31ApplicationTest.java
> +                .isNotNull();
проверка слабая

2024-02-29 08:26 UTC, dmitry-bizin commented on src/test/java/ru/hogwarts/school/Hw31ApplicationTest.java
> +                .isNotNull();
проверка слабая

2024-02-29 08:26 UTC, dmitry-bizin commented on src/test/java/ru/hogwarts/school/Hw31ApplicationTest.java
>          this.restTemplate.delete("http://localhost:" + port + "/student", params);
где проверка?

2024-02-29 08:26 UTC, dmitry-bizin commented on src/test/java/ru/hogwarts/school/Hw31ApplicationTest.java
>          params.put("id", "1");
где проверка после обновления?

2024-02-29 08:27 UTC, dmitry-bizin commented on src/test/java/ru/hogwarts/school/Hw31ApplicationTest.java
>          this.restTemplate.delete("http://localhost:" + port + "/faculty", params);
где проверка после удаления?

2024-02-29 08:27 UTC, dmitry-bizin commented on src/test/java/ru/hogwarts/school/Hw31ApplicationTest.java
>                  .isNotNull();
слабая проверка здесь и выше

2024-03-12 04:52 UTC, dmitry-bizin commented on src/main/java/ru/hogwarts/school/services/AvatarService.java
> +        PageRequest pageRequest = PageRequest.of(page - 1, size);
хорошо бы делать проверку пришедших параметров - что они больше или равны 1

2024-03-12 04:53 UTC, dmitry-bizin commented on src/test/java/ru/hogwarts/school/services/StudentServiceTest.java
> +                .andExpect(jsonPath("$[4].age").value(student5.getAge()));
а если было бы 100 студентов в базе, всех бы так же проверял?) не проще ли получить объект из json и проверить?

2024-03-19 11:51 UTC, dmitry-bizin commented on scripts421.sql
> +    age INTEGER DEFAULT 20,
2 одинаковые колонки?

2024-03-19 11:51 UTC, dmitry-bizin commented on scripts421.sql
> +    name VARCHAR(50) UNIQUE
2 одинаковые колонки?

2024-03-19 11:51 UTC, dmitry-bizin commented on scripts421.sql
> +create table faculties ADD UNIQUE unique_index (`color`, `name`);
запрос неверный

2024-03-19 11:52 UTC, dmitry-bizin commented on src/main/resources/liquibase/scripts/faculty.sql
> +CREATE INDEX faculty_name_color_index ON faculty (name, color)
```suggestion
CREATE INDEX faculty_name_color_index ON faculties (name, color)
```
не во множественном разве?

2024-03-19 14:21 UTC, FeralBerry commented on scripts421.sql
> +    age INTEGER DEFAULT 20,
привет, всё в последнее время впопыхах не заметил.

2024-03-22 08:42 UTC, dmitry-bizin commented on src/main/java/ru/hogwarts/school/controllers/InfoControllerProduction.java
> +@Profile("production")
эта аннотация не нужна, контроллер должен быть один, но надо запускать приложение с разными профилями и смотреть, что подцепляется порт указанного профиля

2024-03-22 08:43 UTC, dmitry-bizin commented on src/main/java/ru/hogwarts/school/controllers/InfoControllerTest.java
> +@Profile("test")
эта аннотация не нужна, контроллер должен быть один, но надо запускать приложение с разными профилями и смотреть, что подцепляется порт указанного профиля

2024-03-22 08:43 UTC, dmitry-bizin commented on src/main/java/ru/hogwarts/school/services/AvatarService.java
> +    Logger logger = LoggerFactory.getLogger(StudentService.class);
```suggestion
    private final Logger logger = LoggerFactory.getLogger(StudentService.class);
```

2024-03-22 08:43 UTC, dmitry-bizin commented on src/main/java/ru/hogwarts/school/services/FacultyService.java
> +    Logger logger = LoggerFactory.getLogger(StudentService.class);
```suggestion
   private final Logger logger = LoggerFactory.getLogger(StudentService.class);
```

2024-03-22 08:43 UTC, dmitry-bizin commented on src/main/java/ru/hogwarts/school/services/StudentService.java
> +    Logger logger = LoggerFactory.getLogger(StudentService.class);
```suggestion
    private final Logger logger = LoggerFactory.getLogger(StudentService.class);
```

2024-03-22 08:44 UTC, dmitry-bizin commented on src/main/resources/application-{test}.properties
у тебя профиль сейчас называется {test}, а должен называться test, т.е. имя файла должно быть application-test.properties

2024-03-27 13:08 UTC, OlgaLugacheva requested changes

2024-03-27 13:08 UTC, OlgaLugacheva commented on src/main/java/ru/hogwarts/school/services/StudentService.java
> +                        .sum() / studentRepository.countStudents());
проще 
  .average()

2024-03-27 14:28 UTC, merged